### ISSUE TITLE
RuntimeError: readexactly() called while another coroutine is already waiting for incoming data 발생

### ISSUE THREAD

**Issue by JungHoon99** [f-lab-edu/sns-media#13]
```
Traceback (most recent call last):
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 14, in __call__
    async with AsyncExitStack() as stack:
  File "/Users/junghun/.pyenv/versions/3.10.11/lib/python3.10/contextlib.py", line 714, in __aexit__
    raise exc_details[1]
  File "/Users/junghun/.pyenv/versions/3.10.11/lib/python3.10/contextlib.py", line 697, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/Users/junghun/.pyenv/versions/3.10.11/lib/python3.10/contextlib.py", line 206, in __aexit__
    await anext(self.gen)
  File "/Users/junghun/PycharmProjects/sns-media/src/apis/dependencies.py", line 7, in get_session
    async with AsyncSession(engine) as session:
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 1080, in __aexit__
    await asyncio.shield(task)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 1025, in close
    await greenlet_spawn(self.sync_session.close)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2518, in close
    self._close_impl(invalidate=False)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2587, in _close_impl
    transaction.close(invalidate)
  File "<string>", line 2, in close
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1419, in close
    transaction.close()
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2588, in close
    self._do_close()
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2726, in _do_close
    self._close_impl()
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2712, in _close_impl
    self._connection_rollback_impl()
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2704, in _connection_rollback_impl
    self.connection._rollback_impl()
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1129, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2358, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1127, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 699, in do_rollback
    dbapi_connection.rollback()
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/aiomysql.py", line 201, in rollback
    self.await_(self._connection.rollback())
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/aiomysql/connection.py", line 399, in rollback
    await self._read_ok_packet()
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/aiomysql/connection.py", line 372, in _read_ok_packet
    pkt = await self._read_packet()
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/aiomysql/connection.py", line 609, in _read_packet
    packet_header = await self._read_bytes(4)
  File "/Users/junghun/PycharmProjects/sns-media/.venv/lib/python3.10/site-packages/aiomysql/connection.py", line 657, in _read_bytes
    data = await self._reader.readexactly(num_bytes)
  File "/Users/junghun/.pyenv/versions/3.10.11/lib/python3.10/asyncio/streams.py", line 708, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/junghun/.pyenv/versions/3.10.11/lib/python3.10/asyncio/streams.py", line 487, in _wait_for_data
    raise RuntimeError(
RuntimeError: readexactly() called while another coroutine is already waiting for incoming data
```
FastAPI와 SQLAlchemy를 사용하여 비동기 데이터베이스 연동을 구현하는 도중, RuntimeError가 발생했습니다. 이 오류는 readexactly() 메서드를 호출하는 동안 다른 코루틴이 동일한 스트림에서 데이터를 기다리고 있는 경우 발생합니다.

**Comment by JungHoon99** [comment]
`pool_size=20`, `max_overflow=20`, `pool_pre_ping=True`, `pool_recycle=500`,옵션을 사용해서 해결 

- `pool_size`는 연결할 수 있는 connection_pool에 대한 개수를 뜻합니다. `pool_size`까지는 더 연결이 필요하지 않은 상황이라도 연결을 종료하지 않습니다. 풀링을 비활성화 하려면 NullPool을 사용합니다.
- `max_overflow`는 풀의 최대 오버플로 크기로 체크아웃된 연결 수가 `pool_size`에 설정된 크기에 도달하면 이 제한까지 추가 연결이 반환됩니다. `max_overflow` 사이즈가 작으면 TimeoutError를 쉽게 만난다거나 서비스 속도 저하를 자주 경험하게 됩니다. 그렇다고 무한으로 둔다면 데이터베이스가 죽을 수 있습니다.
- `pool_pre_ping`는 `SELECT 1`이나 DBAPI전용 핑 방법을 사용해 `connection_pool`이 살아있는지 아닌기 테스트하는 것
<img width="765" alt="image" src="https://github.com/user-attachments/assets/0c3b9ac5-9911-4dc7-91a1-c6766d96b17d">

- `pool_recycle`은 mysql의 경우 일정 시간동안 connection이 없을 경우 connection을 끊어버리게 되는데 `pool_recycle`을 설정한 시간동안 connection을 유지하게 된다.

**Comment by JungHoon99** [comment]
참고한 블로그와 공식문서입니다.
- https://spoqa.github.io/2018/01/17/connection-pool-of-sqlalchemy.html
- https://jakpentest.tistory.com/entry/SQLAlchemy-Connection-%EC%84%A4%EC%A0%95%EC%97%90-%EA%B4%80%ED%95%9C-%EC%A0%95%EB%A6%AC
- https://velog.io/@shyim/SQLAlchemy-error-MySQL-server-has-gone-away
- https://yujuwon.tistory.com/entry/SQLALCHEMY-session-%EA%B4%80%EB%A6%AC
- https://docs.sqlalchemy.org/en/14/core/pooling.html
